/**
 * Export report as a print-ready document using the browser's print API.
 * Opens a styled popup window with the formatted report and triggers print.
 */
export function exportReport(reportData) {
  const { incident_record, advice, navigation } = reportData;

  const severityLabel = {
    high: 'High',
    medium: 'Medium',
    low: 'Low',
  }[incident_record?.severity_indicator] || 'Unknown';

  const severityColor = {
    high: '#dc2626',
    medium: '#d97706',
    low: '#16a34a',
  }[incident_record?.severity_indicator] || '#64748b';

  const stepsHtml = (navigation?.reporting_steps || [])
    .map(s => `<li style="margin-bottom:8px"><strong>Step ${s.step_number}:</strong> ${s.action}<br><em style="color:#64748b;font-size:12px">${s.estimated_timeline}</em></li>`)
    .join('');

  const html = `<!DOCTYPE html>
<html>
<head>
  <title>Witness Report</title>
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; padding: 40px; color: #1e293b; line-height: 1.6; max-width: 700px; margin: 0 auto; }
    h1 { font-size: 24px; margin-bottom: 4px; }
    h2 { font-size: 16px; color: #6366f1; margin-top: 24px; margin-bottom: 8px; text-transform: uppercase; letter-spacing: 0.5px; border-bottom: 2px solid #e2e8f0; padding-bottom: 4px; }
    .subtitle { color: #64748b; font-size: 13px; margin-bottom: 24px; }
    .grid { display: grid; grid-template-columns: 1fr 1fr; gap: 12px; margin-bottom: 16px; }
    .field { background: #f8fafc; border-radius: 8px; padding: 10px 14px; }
    .field-label { font-size: 11px; color: #94a3b8; text-transform: uppercase; letter-spacing: 0.5px; }
    .field-value { font-size: 14px; font-weight: 600; }
    .severity { display: inline-block; padding: 2px 10px; border-radius: 12px; font-size: 12px; font-weight: 700; color: white; }
    .summary { background: #f8fafc; border-radius: 8px; padding: 14px; font-size: 14px; margin-bottom: 8px; }
    .draft { background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 8px; padding: 14px; font-size: 14px; white-space: pre-wrap; }
    ol { padding-left: 20px; font-size: 14px; }
    .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e2e8f0; color: #94a3b8; font-size: 11px; text-align: center; }
    @media print { body { padding: 20px; } }
  </style>
</head>
<body>
  <h1>Witness Report</h1>
  <p class="subtitle">Anonymous Bias Incident Report — Virginia Tech<br>Generated ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>

  <h2>Incident Record</h2>
  <div class="grid">
    <div class="field"><div class="field-label">Type</div><div class="field-value">${(incident_record?.incident_type || '—').replace('_', ' ')}</div></div>
    <div class="field"><div class="field-label">Bias Category</div><div class="field-value">${(incident_record?.bias_category || '—').replace('_', ' ')}</div></div>
    <div class="field"><div class="field-label">When</div><div class="field-value">${incident_record?.date_context || 'Not specified'}</div></div>
    <div class="field"><div class="field-label">Where</div><div class="field-value">${incident_record?.location_context || 'Not specified'}</div></div>
  </div>
  <p style="margin-bottom:8px"><strong>Severity:</strong> <span class="severity" style="background:${severityColor}">${severityLabel}</span></p>
  <div class="summary">${incident_record?.description_summary || '—'}</div>

  ${advice ? `
  <h2>Your Rights</h2>
  <p style="margin-bottom:8px"><strong>Applicable Policy:</strong> ${advice.matched_policy}</p>
  <p style="font-size:14px;margin-bottom:8px">${advice.rights_summary}</p>
  <p style="font-size:14px"><strong>Contact:</strong> ${advice.vt_contact?.office || ''} — <a href="${advice.vt_contact?.url || '#'}">${advice.vt_contact?.url || ''}</a></p>
  ` : ''}

  ${navigation ? `
  <h2>Reporting Steps</h2>
  <ol>${stepsHtml}</ol>

  <h2>Draft Statement</h2>
  <div class="draft">${navigation.draft_statement || '—'}</div>
  ` : ''}

  <div class="footer">
    This document was generated by Witness — an anonymous AI-powered bias reporting tool for Virginia Tech students.<br>
    No personal information is stored. Report auto-deletes after 90 days.
  </div>
</body>
</html>`;

  const printWindow = window.open('', '_blank', 'width=800,height=900');
  if (printWindow) {
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => printWindow.print(), 300);
  }
}
